databases:
  - name: ipay
    databaseName: ipay
    user: ipay

services:
  - type: web
    name: ipay
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ipay
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false